### ISSUE TITLE
Possible Multiple Sample Issue?

### ISSUE THREAD

**Issue by bcantarel** [tvandervalk/AMBER#2]
I only have 1 BAM file
/usr/local/lib/python3.10/dist-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "

----------------------------------------------------------------------
Processing sample: Sample
Traceback (most recent call last):
  File "/usr/local/bin/AMBER", line 114, in <module>
    if splitted[1] == sample_name:
IndexError: list index out of range

**Comment by tvandervalk** [comment]
@bcantarel thanks for bringing this to my attention. It has now been fixed.
