### ISSUE TITLE
Non-ASCII character

### ISSUE THREAD

**Issue by bcantarel** [tvandervalk/AMBER#3]
root@1e7a2ab4d1ad:/data# python /usr/local/bin/AMBER --bamfiles test
  File "/usr/local/bin/AMBER", line 44
SyntaxError: Non-ASCII character '\xe2' in file /usr/local/bin/AMBER on line 44, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by tvandervalk** [comment]
resolved
